# -*- coding: utf-8 -*-
"""project_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_miEDFHTHBKquNdDX8YkT3CV5EnXhQ0d
"""

!pip install kneed

"""# Credit Card Customer Segmentation
## Unsupervised Machine Learning Project

**Dataset:** CC_GENERAL.csv  
**Goal:** Discover customer segments based on credit card usage behavior
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

"""## 1. Dataset Overview"""

df = pd.read_csv("CC GENERAL.csv")
print("shape",df.shape)
df.head

# Data types
df.info()

# Statistical summary
df.describe().round(2)

"""## 2. Missing Values"""

missing = df.isnull().sum()
missing_percent = (df.isnull().sum()/len(df))*100

missing_df = pd.DataFrame({
    'Missing Count':missing,
    'Percentage':missing_percent
})

print(missing_df[missing_df['Missing Count']>0])

print("Duplicate rows:",df.duplicated().sum())

"""## 3. Feature Distributions"""

df.drop('CUST_ID',axis=1).hist(figsize=(18,14),color='steelblue',edgecolor='black')
plt.suptitle('Distribution of All Features',fontsize = 16)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\feature_distributions.png")

"""## 4. Outlier Detection"""

fig,axes = plt.subplots(3,3,figsize=(16,12))
cols = ['BALANCE','PURCHASES','CASH_ADVANCE','CREDIT_LIMIT','PAYMENTS','MINIMUM_PAYMENTS','PURCHASES_TRX','CASH_ADVANCE_TRX','TENURE']
for i,col in enumerate(cols):
    axes[i//3][i%3].boxplot(df[col].dropna())
    axes[i//3][i%3].set_title(col)

plt.suptitle('Boxplots - Outlier Detection',fontsize =14)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\outliers_boxplot.png")

"""## 5. Correlation Between Features"""

plt.figure(figsize=(16,10))
corr = df.drop('CUST_ID',axis=1).corr()
sns.heatmap(corr,annot=True,fmt='.2f',cmap='coolwarm',linewidths=0.5)
plt.title('Correlation Heatmap',fontsize = 14)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\correlation_heatmap.png")

"""## 6. EDA Key Observations

- Dataset has **8,950 customers** and **18 features**
- **CUST_ID** is just an identifier — will be dropped during preprocessing
- **MINIMUM_PAYMENTS** has 313 missing values (~3.5%) — will fill with median
- **CREDIT_LIMIT** has 1 missing value — will fill with median
- **No duplicate rows** found
- Features like BALANCE, CASH_ADVANCE, PURCHASES are **heavily right-skewed** — will need scaling
- Strong correlation found between **PURCHASES and ONEOFF_PURCHASES**
- Strong correlation between **PURCHASES_FREQUENCY and PURCHASES_INSTALLMENTS_FREQUENCY**

## 4. Data Preprocessing

In this section we clean the raw dataset by:
- Dropping irrelevant columns
- Handling missing values
- Capping outliers
"""

from preprocessing import preprocess_pipeline, scale_features
from feature_engineering import create_derived_features, apply_pca

# Load and preprocess
df_clean = preprocess_pipeline('CC GENERAL.csv')

print("Shape after preprocessing:", df_clean.shape)
print("\nMissing values remaining:", df_clean.isnull().sum().sum())
df_clean.head()

# Boxplots after outlier capping
fig, axes = plt.subplots(2, 3, figsize=(14, 8))
cols = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE',
        'CREDIT_LIMIT', 'PAYMENTS', 'MINIMUM_PAYMENTS']

for i, col in enumerate(cols):
    axes[i//3][i%3].boxplot(df_clean[col])
    axes[i//3][i%3].set_title(f'{col} - After Capping')

plt.suptitle('Boxplots After Outlier Capping', fontsize=13)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\correlation_heatmap.png")
plt.show()

"""### Preprocessing Decisions
- Dropped **CUST_ID** — identifier column, not useful for clustering
- Filled **MINIMUM_PAYMENTS** nulls with median — 313 missing values
- Filled **CREDIT_LIMIT** null with median — 1 missing value
- Used **median** not mean because data is heavily right skewed
- Used **IQR Capping** for outliers — caps extreme values without removing customers
- No duplicates found so no action needed

## 5. Feature Engineering

Creating new derived features to help clustering algorithms
find better and more meaningful patterns.
"""

df_engineered = create_derived_features(df_clean.copy())
print('Shape after feature engineering',df_engineered.shape)
print("\nNew features added:")
new_cols = ['MONTHLY_AVG_PURCHASE', 'MONTHLY_AVG_CASH_ADVANCE','PURCHASE_TO_LIMIT_RATIO', 'CASH_ADVANCE_TO_LIMIT_RATIO','BALANCE_TO_LIMIT_RATIO']
df_engineered[new_cols].describe().round(3)

df_scaled,scaler = scale_features(df_engineered)
print('Scaling done! Shape:',df_scaled.shape)
df_scaled.head()

pca_df,pca_model = apply_pca(df_scaled,n_components=2)
plt.figure(figsize=(8,6))
plt.scatter(pca_df['PCA1'],pca_df['PCA2'],alpha=0.3,color = 'steelblue',s=10)
plt.title('PCA - 2D View of Customer Data')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.tight_layout()
plt.savefig(r'/content/C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\pca_visualization.png')

df_engineered.to_csv('processed.csv',index=False)
print("Processed data saved to data/processed/ folder!")

"""### Feature Engineering Decisions
- **MONTHLY_AVG_PURCHASE** — actual spending per month normalized by tenure
- **MONTHLY_AVG_CASH_ADVANCE** — cash dependency per month
- **PURCHASE_TO_LIMIT_RATIO** — how actively credit limit is used for purchases
- **CASH_ADVANCE_TO_LIMIT_RATIO** — cash advance dependency relative to limit
- **BALANCE_TO_LIMIT_RATIO** — how leveraged the customer is
- **PCA** applied to 2 components for visualization purposes only

## 6. Clustering Experiments

We apply two clustering algorithms:
1. **K-Means** — partitions customers into K groups by minimizing distance
2. **Hierarchical Clustering** — builds a tree of clusters from bottom up

First we find the optimal number of clusters using Elbow Method and Silhouette Score.
"""

from clustering import (find_optimal_k,plot_elbow_silhouette,run_kmeans,run_hierarchical,plot_clusters,save_model)

# Find optimal K
optimal_k, inertias, sil_scores, k_range = find_optimal_k(df_scaled.values)

# Plot elbow and silhouette
plot_elbow_silhouette(k_range, inertias, sil_scores, optimal_k)

"""### Elbow and Silhouette Observation
- Inertia drops sharply at first then flattens out
- The point where the curve bends is the optimal K
- Silhouette score confirms the best K value
"""

# Run KMeans with optimal K

kmeans_labels,kmeans_model = run_kmeans(df_scaled.values,optimal_k)

# Visualize

plot_clusters(pca_df,kmeans_labels,'KMeans Clustering')

# Save model

save_model(kmeans_model,'kmeans_model')

hierarchical_labels = run_hierarchical(df_scaled.values,optimal_k)
plot_clusters(pca_df,hierarchical_labels,'Hierarchical Clustering')

df_engineered['KMeans_Cluster'] = kmeans_labels
df_engineered['Hierarchical_Cluster'] = hierarchical_labels

print("Cluster labels added!")
print("\nKMeans cluster distribution:")
print(df_engineered['KMeans_Cluster'].value_counts().sort_index())
print("\nHierarchical cluster distribution:")
print(df_engineered['Hierarchical_Cluster'].value_counts().sort_index())

"""### Clustering Observations
- KMeans produced clear and well separated clusters in PCA plot
- Hierarchical clustering produced similar groupings to KMeans
- Both algorithms used the same K value for fair comparison
- KMeans is faster and more suitable for large datasets like this one

## 7. Cluster Evaluation

We evaluate clustering quality using:
- **Silhouette Score** — how similar a point is to its own cluster vs other clusters. Higher is better. Range -1 to 1.
- **Davies-Bouldin Index** — average similarity between clusters. Lower is better. Min is 0.
- **Visual Silhouette Plot** — shows silhouette score per cluster visually.
"""

from evaluation import (evaluate_clustering,compare_algorithms,plot_evaluation,plot_silhouette_per_cluster)

print("Import successful!")

results = compare_algorithms(df_scaled.values,kmeans_labels, hierarchical_labels)

plot_evaluation(results)

plot_silhouette_per_cluster(df_scaled.values,kmeans_labels,'KMeans')

plot_silhouette_per_cluster(df_scaled.values,
                            hierarchical_labels,
                            'Hierarchical')

"""### Evaluation Results Summary

**Silhouette Score:**
- Measures how well each customer fits in their assigned cluster
- Score closer to 1 means clusters are well separated
- Score closer to 0 means clusters are overlapping

**Davies-Bouldin Index:**
- Measures average similarity ratio between clusters
- Lower score means clusters are more distinct from each other

**Conclusion:**
- KMeans produced better defined clusters than Hierarchical Clustering
- KMeans will be used for final cluster interpretation
- Silhouette plot shows most customers have positive scores meaning good cluster fit

## 8. Cluster Interpretation

In this section we analyze each cluster in detail:
- Identify key characteristics of each cluster
- Compare clusters across important features
- Assign a descriptive label to each cluster
- Explain real world significance
"""

# Add KMeans labels to engineered dataframe
df_engineered['Cluster'] = kmeans_labels

# Get mean values for each cluster
cluster_profile = df_engineered.groupby('Cluster').mean().round(2)
print("Cluster Profiles:")
cluster_profile

# How many customers in each cluster

cluster_sizes = df_engineered['Cluster'].value_counts().sort_index()
print("Cluster Size :")
print(cluster_sizes)

# Plot cluster sizes

plt.figure(figsize=(8,5))
cluster_sizes.plot(kind = 'bar',color = 'steelblue',edgecolor = 'black' )
plt.title('Number of Customers per Cluster')
plt.xlabel('Cluster')
plt.ylabel('Number of Customers')
plt.tight_layout()
plt.savefig(r'C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\cluster_sizes.png')

# Compare clusters on most important features
key_features = [
    'BALANCE',
    'PURCHASES',
    'CASH_ADVANCE',
    'CREDIT_LIMIT',
    'PAYMENTS',
    'PRC_FULL_PAYMENT',
    'PURCHASE_TO_LIMIT_RATIO',
    'MONTHLY_AVG_PURCHASE'
]

fig, axes = plt.subplots(4, 2, figsize=(14, 16))

for i, feature in enumerate(key_features):
    ax = axes[i//2][i%2]
    data = [df_engineered[df_engineered['Cluster'] == c][feature].values
            for c in sorted(df_engineered['Cluster'].unique())]
    ax.boxplot(data, labels=[f'C{c}' for c in sorted(df_engineered['Cluster'].unique())])
    ax.set_title(feature)
    ax.set_xlabel('Cluster')

plt.suptitle('Feature Comparison Across Clusters', fontsize=14)
plt.tight_layout()
plt.savefig(r'C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\cluster_feature_comparison.png')
plt.show()

# Normalize for better visualization

from sklearn.preprocessing import  MinMaxScaler

key_cols = ['BALANCE','PURCHASES','CASH_ADVANCE','CREDIT_LIMIT','PAYMENTS','PRC_FULL_PAYMENT','MONTHLY_AVG_PURCHASE','MONTHLY_AVG_CASH_ADVANCE','PURCHASE_TO_LIMIT_RATIO','BALANCE_TO_LIMIT_RATIO']

profile = df_engineered.groupby('Cluster')[key_cols].mean()
scaler_mm = MinMaxScaler()
profile_normalized = pd.DataFrame(scaler_mm.fit_transform(profile),
                                  index = profile.index,
                                  columns=profile.columns
                                  )

plt.figure(figsize=(12,6))
sns.heatmap(profile_normalized,annot=True,fmt ='.2f',cmap='YlOrRd',linewidths=0.5)
plt.title('Cluster Profile Heatmap (Normalized)',fontsize=13)
plt.tight_layout()
plt.savefig(r'C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\cluster_heatmap.png')

for c in sorted(df_engineered['Cluster'].unique()):
  cluster_data = df_engineered[df_engineered['Cluster'] == c]
  print(f"{'='*50}")
  print(f"CLUSTER {c}")
  print(f"{'=' * 50}")
  print(f"size:{len(cluster_data)}customers")
  print(f"Avg Balance :{cluster_data['BALANCE'].mean():.2f}")
  print(f"Avg Purchases : {cluster_data['PURCHASES'].mean():.2f}")
  print(f"Avg Cash Advance :{cluster_data['CASH_ADVANCE'].mean():.2f}")
  print(f"Avg Credit Limit :{cluster_data['CREDIT_LIMIT'].mean():.2f}")
  print(f"Avg Full Payment :{cluster_data['PRC_FULL_PAYMENT'].mean():.2f}")
  print()

"""### Cluster Labels and Descriptions

| Cluster | Label | Key Characteristics |
|---|---|---|
| 0 |  Inactive Users | Low balance, low purchases, rarely use card |
| 1 |  Active Purchasers | High purchases, low cash advance, pay regularly |
| 2 |  Cash Advance Users | High cash advance, low purchases, high balance |
| 3 |  High Value Customers | High credit limit, high purchases, pay in full |

### Real World Significance

**Cluster 0 — Inactive Users:**
- Customers who rarely use their credit card
- Bank should send offers and rewards to activate them
- Low risk but low revenue generators

**Cluster 1 — Active Purchasers:**
- Regular spenders who use card for purchases
- Good customers who pay their bills on time
- Bank should offer cashback and loyalty rewards

**Cluster 2 — Cash Advance Users:**
- Customers who rely heavily on cash advances
- Carry high balance — financially stressed
- Bank should offer financial counseling or lower interest plans

**Cluster 3 — High Value Customers:**
- Premium customers with high credit limits
- Pay full balance regularly — very low risk
- Bank should offer premium cards and exclusive benefits
"""

df_engineered['Cluster_Label'] = df_engineered['Cluster'].map({0:'Inactive Users',1:'Active Purchasers',2 : 'Cash Advance Users',3 : 'High Value Customers'})
df_engineered.to_csv('dataset_with_clusters.csv',index=False)
print('Final dataset saved')
print()
print(df_engineered['Cluster_Label'].value_counts())

"""## 9. Key Insights

1. **4 distinct customer segments** were identified from 8950 customers

2. **Inactive Users** form the largest group — bank has big opportunity
to activate them

3. **Cash Advance Users** are financially stressed — highest risk for bank

4. **Active Purchasers** are the most valuable day-to-day customers

5. **High Value Customers** pay in full every month — lowest risk

6. **KMeans** outperformed Hierarchical Clustering on Silhouette Score

7. **Feature engineering** helped reveal clearer patterns

### Business Recommendations
- Target **Inactive Users** with activation campaigns and welcome offers
- Offer **Active Purchasers** loyalty rewards and cashback programs
- Provide **Cash Advance Users** with debt management products
- Give **High Value Customers** premium services and exclusive cards

## Pipeline and Final Run

Running the complete pipeline end to end using pipeline.py
"""

from pipeline import run_full_pipeline

df_result, model, scaler = run_full_pipeline(
    data_path='CC GENERAL.csv',
    n_clusters=4
)

