# -*- coding: utf-8 -*-
"""project_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_miEDFHTHBKquNdDX8YkT3CV5EnXhQ0d

# Credit Card Customer Segmentation
## Unsupervised Machine Learning Project

**Dataset:** CC_GENERAL.csv  
**Goal:** Discover customer segments based on credit card usage behavior
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

"""## 1. Dataset Overview"""

df = pd.read_csv("CC GENERAL.csv")
print("shape",df.shape)
df.head

# Data types
df.info()

# Statistical summary
df.describe().round(2)

"""## 2. Missing Values"""

missing = df.isnull().sum()
missing_percent = (df.isnull().sum()/len(df))*100

missing_df = pd.DataFrame({
    'Missing Count':missing,
    'Percentage':missing_percent
})

print(missing_df[missing_df['Missing Count']>0])

print("Duplicate rows:",df.duplicated().sum())

"""## 3. Feature Distributions"""

df.drop('CUST_ID',axis=1).hist(figsize=(18,14),color='steelblue',edgecolor='black')
plt.suptitle('Distribution of All Features',fontsize = 16)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\feature_distributions.png")

"""## 4. Outlier Detection"""

fig,axes = plt.subplots(3,3,figsize=(16,12))
cols = ['BALANCE','PURCHASES','CASH_ADVANCE','CREDIT_LIMIT','PAYMENTS','MINIMUM_PAYMENTS','PURCHASES_TRX','CASH_ADVANCE_TRX','TENURE']
for i,col in enumerate(cols):
    axes[i//3][i%3].boxplot(df[col].dropna())
    axes[i//3][i%3].set_title(col)

plt.suptitle('Boxplots - Outlier Detection',fontsize =14)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\outliers_boxplot.png")

"""## 5. Correlation Between Features"""

plt.figure(figsize=(16,10))
corr = df.drop('CUST_ID',axis=1).corr()
sns.heatmap(corr,annot=True,fmt='.2f',cmap='coolwarm',linewidths=0.5)
plt.title('Correlation Heatmap',fontsize = 14)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\correlation_heatmap.png")

"""## 6. EDA Key Observations

- Dataset has **8,950 customers** and **18 features**
- **CUST_ID** is just an identifier — will be dropped during preprocessing
- **MINIMUM_PAYMENTS** has 313 missing values (~3.5%) — will fill with median
- **CREDIT_LIMIT** has 1 missing value — will fill with median
- **No duplicate rows** found
- Features like BALANCE, CASH_ADVANCE, PURCHASES are **heavily right-skewed** — will need scaling
- Strong correlation found between **PURCHASES and ONEOFF_PURCHASES**
- Strong correlation between **PURCHASES_FREQUENCY and PURCHASES_INSTALLMENTS_FREQUENCY**

## 4. Data Preprocessing

In this section we clean the raw dataset by:
- Dropping irrelevant columns
- Handling missing values
- Capping outliers
"""

import sys
sys.path.append('../src')

from preprocessing import preprocess_pipeline, scale_features
from feature_engineering import create_derived_features, apply_pca

# Load and preprocess
df_clean = preprocess_pipeline('CC GENERAL.csv')

print("Shape after preprocessing:", df_clean.shape)
print("\nMissing values remaining:", df_clean.isnull().sum().sum())
df_clean.head()

# Boxplots after outlier capping
fig, axes = plt.subplots(2, 3, figsize=(14, 8))
cols = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE',
        'CREDIT_LIMIT', 'PAYMENTS', 'MINIMUM_PAYMENTS']

for i, col in enumerate(cols):
    axes[i//3][i%3].boxplot(df_clean[col])
    axes[i//3][i%3].set_title(f'{col} - After Capping')

plt.suptitle('Boxplots After Outlier Capping', fontsize=13)
plt.tight_layout()
plt.savefig(r"C:\Users\user\OneDrive\Desktop\ML\Credit Card\outputs\reports\correlation_heatmap.png")
plt.show()

"""### Preprocessing Decisions
- Dropped **CUST_ID** — identifier column, not useful for clustering
- Filled **MINIMUM_PAYMENTS** nulls with median — 313 missing values
- Filled **CREDIT_LIMIT** null with median — 1 missing value
- Used **median** not mean because data is heavily right skewed
- Used **IQR Capping** for outliers — caps extreme values without removing customers
- No duplicates found so no action needed

## 5. Feature Engineering

Creating new derived features to help clustering algorithms
find better and more meaningful patterns.
"""

df_engineered = create_derived_features(df_clean.copy())
print('Shape after feature engineering',df_engineered.shape)
print("\nNew features added:")
new_cols = ['MONTHLY_AVG_PURCHASE', 'MONTHLY_AVG_CASH_ADVANCE','PURCHASE_TO_LIMIT_RATIO', 'CASH_ADVANCE_TO_LIMIT_RATIO','BALANCE_TO_LIMIT_RATIO']
df_engineered[new_cols].describe().round(3)

df_scaled,scaler = scale_features(df_engineered)
print('Scaling done! Shape:',df_scaled.shape)
df_scaled.head()

pca_df,pca_model = apply_pca(df_scaled,n_components=2)
plt.figure(figsize=(8,6))
plt.scatter(pca_df['PCA1'],pca_df['PCA2'],alpha=0.3,color = 'steelblue',s=10)
plt.title('PCA - 2D View of Customer Data')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.tight_layout()
plt.savefig('pca_visualization.png')

df_engineered.to_csv('processed.csv',index=False)
print("Processed data saved to data/processed/ folder!")

"""### Feature Engineering Decisions
- **MONTHLY_AVG_PURCHASE** — actual spending per month normalized by tenure
- **MONTHLY_AVG_CASH_ADVANCE** — cash dependency per month
- **PURCHASE_TO_LIMIT_RATIO** — how actively credit limit is used for purchases
- **CASH_ADVANCE_TO_LIMIT_RATIO** — cash advance dependency relative to limit
- **BALANCE_TO_LIMIT_RATIO** — how leveraged the customer is
- **PCA** applied to 2 components for visualization purposes only
"""

