# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSBo2sU7eAdyKKA8TagvVrhvF0Wxmv6r
"""

import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans,AgglomerativeClustering
from sklearn.metrics import silhouette_score
from kneed import KneeLocator
import joblib

def find_optimal_k(scaled_data,max_k=10):
  inertias = []
  silhouette_scores=[]
  k_range = range(2,max_k +1)


  for k in k_range:
    km = KMeans(n_clusters=k,random_state=42,n_init=10)
    km.fit(scaled_data)
    inertias.append(km.inertia_)
    silhouette_score.append(silhouette_score(scaled_data,km.labels_))


  knee = KneeLocator(list(k_range),inertias,curve='convex',direction='decreasing')
  optimal_k = knee.knee


  print(f"Optimal K from Elbow method: {optimal_k}")
  return optimal_k, inertias, silhouette_scores, list(k_range)


  def plot_elbow_silhoutte(k_range,inertias,silhouette_score,optimal_k):
    fig,axes =plt.subplots(1,2,figsize=(14,5))

  # Elbow plot

  axes[0].plot(k_range,inertias,marker ='o',color ='steelblue')
  axes[0].axvline(x=optimal_k,color ='red',linestyle='--',label = f'optimal K = {optimal_k}')
  axes[0].set_title('Elbow Method')
  axes[0].set_xlabel('Number of Clusters (K)')
  axes[0].set_ylabel('inertia')
  axes[0].legend()


  # Silhouette plot

  axes[1].plot(k_range,silhouette_score,markr = 'o',color ='green')
  axes[1].axvline(x=optimal_k,color='red',linestyle='--',label = f'optimal K = {optimal_k}')
  axes[1].set_title('Silhouette Scores')
  axes[1].set_xlabel('Number of Clusters (K)')
  axes[1].set_ylabel('Silhouette Score')
  axes[1].legend()

  plt.suptitle('Finding Optimal Number of Clusters',fontsize = 13)
  plt.tight_layout()
  plt.savefig('elbow_silhouette.png')

def run_kmens(scaled_data,k):
  km = KMeans(n_clusters=k,random_state=42,n_init=10)
  labels = km.fit(scaled_data)
  print(f"KMeans completed with K={k}")
  print(f"Cluster sizes:\n{pd.Series(labels).value_counts().sort_index()}")

  return labels,km


def run_hierarchical(scaled_data,k):
  hc = AgglomerativeClustering(n_clusters=k)
  labels = hc.fit_predict(scaled_data)
  print(f'Hierarchical Clustering completed with K={k}')
  print('Cluster sizes:\n{pd.Series(labels).value_counts().sort_index()}')
  return labels



def plot_clusters(pca_df,labels,title):
  plt.figure(figsize=(8,6))
  scatter = plt.scatter(pca_df['PCA1'],pca_df['PCA2'],c = labels,cmap='tab10',alpha=0.5,s=10)
  plt.colorbar(scatter)
  plt.title(title)

  plt.xlabel('PCA Component 1')
  plt.ylabel('PCA Component 2')
  plt.tight_layout()
  filename = title.lower().replace(' ','_')
  plt.savefig(f'../outputs/reports/{filename}.png')


def save_model(model,filename):
  joblib.dump(model, f'../outputs/models/{filename}.pkl')
  print(f"Model saved: {filename}.pkl")

