# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNTmpvYzfXMHQR3Uy5A2rVWPJSYzd8ay
"""

import pandas as pd
import numpy as np

from sklearn.decomposition import PCA

def create_derived_features(df):
    # How much customer spends per month
    df['MONTHLY_AVG_PURCHASE'] = df['PURCHASES'] / df['TENURE']

    # How much cash advance per month
    df['MONTHLY_AVG_CASH_ADVANCE'] = df['CASH_ADVANCE'] / df['TENURE']

    # How much of credit limit is used for purchases
    df['PURCHASE_TO_LIMIT_RATIO'] = df['PURCHASES'] / (df['CREDIT_LIMIT'] + 1)

    # How much of credit limit is used for cash advance
    df['CASH_ADVANCE_TO_LIMIT_RATIO'] = df['CASH_ADVANCE'] / (df['CREDIT_LIMIT'] + 1)

    # Balance compared to credit limit
    df['BALANCE_TO_LIMIT_RATIO'] = df['BALANCE'] / (df['CREDIT_LIMIT'] + 1)

    return df

def apply_pca(scaled_df, n_components=2):
    pca = PCA(n_components=n_components)
    pca_result = pca.fit_transform(scaled_df)
    pca_df = pd.DataFrame(pca_result, columns=['PCA1', 'PCA2'])
    print(f"Explained Variance per component: {pca.explained_variance_ratio_}")
    print(f"Total Variance Captured: {sum(pca.explained_variance_ratio_)*100:.2f}%")
    return pca_df, pca

