# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161WPinY9PDRPpJpWCxZyWtoBWcxDaWQ2
"""

!pip install kneed

import numpy as np
import pandas as pd

from preprocessing import preprocess_pipeline,scale_features
from feature_engineering import create_derived_features,apply_pca
from clustering import run_kmeans,run_hierarchical,plot_clusters,save_model
from evaluation import compare_algorithms,plot_evaluation,plot_silhouette_per_cluster

def run_full_pipeline(data_path, n_clusters=4):
    print("=" * 50)
    print("   CREDIT CARD CUSTOMER SEGMENTATION PIPELINE")
    print("=" * 50)

    # Step 1 - Preprocessing
    print("\n[1/5] Preprocessing data...")
    df_clean = preprocess_pipeline(data_path)
    print(f"      Shape after preprocessing: {df_clean.shape}")

    # Step 2 - Feature Engineering
    print("\n[2/5] Engineering features...")
    df_engineered = create_derived_features(df_clean.copy())
    print(f"      Shape after feature engineering: {df_engineered.shape}")

    # Step 3 - Scaling and PCA
    print("\n[3/5] Scaling features and applying PCA...")
    df_scaled, scaler = scale_features(df_engineered)
    pca_df, pca_model = apply_pca(df_scaled, n_components=2)
    print(f"      Scaling and PCA done!")

    # Step 4 - Clustering
    print(f"\n[4/5] Running clustering with K={n_clusters}...")
    kmeans_labels, kmeans_model = run_kmeans(df_scaled.values, n_clusters)
    hierarchical_labels = run_hierarchical(df_scaled.values, n_clusters)
    plot_clusters(pca_df, kmeans_labels, 'KMeans Clustering')
    plot_clusters(pca_df, hierarchical_labels, 'Hierarchical Clustering')
    save_model(kmeans_model, 'kmeans_model')

    # Step 5 - Evaluation
    print("\n[5/5] Evaluating clusters...")
    results = compare_algorithms(df_scaled.values, kmeans_labels, hierarchical_labels)
    plot_evaluation(results)
    plot_silhouette_per_cluster(df_scaled.values, kmeans_labels, 'KMeans')

    # Save final dataset
    df_engineered['Cluster'] = kmeans_labels
    df_engineered['Cluster_Label'] = df_engineered['Cluster'].map({
        0: 'Inactive Users',
        1: 'Active Purchasers',
        2: 'Cash Advance Users',
        3: 'High Value Customers'
    })
    df_engineered.to_csv('/content/dataset_with_clusters.csv', index=False)

    print("\n" + "=" * 50)
    print("   PIPELINE COMPLETED SUCCESSFULLY!")
    print("=" * 50)
    print(f"\nFinal cluster distribution:")
    print(df_engineered['Cluster_Label'].value_counts())

    return df_engineered, kmeans_model, scaler

if __name__ == "__main__":
    run_full_pipeline('CC GENERAL.csv', n_clusters=4)

