# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkJ7yJ5cvDkUsPUcPy-_Zq2kpTVv4f_b
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

def load_data(path):
    df = pd.read_csv(path)
    return df

def remove_unnecessary_columns(df):
    # CUST_ID is just an identifier not useful for clustering
    df = df.drop('CUST_ID', axis=1)
    return df

def handle_missing_values(df):
    # Using median because data is skewed with outliers
    # Median is not affected by extreme values unlike mean
    df['MINIMUM_PAYMENTS'].fillna(df['MINIMUM_PAYMENTS'].median(), inplace=True)
    df['CREDIT_LIMIT'].fillna(df['CREDIT_LIMIT'].median(), inplace=True)
    return df

def handle_outliers(df):
    # Columns with heavy outliers detected during EDA
    outliers_cols = [
        'BALANCE', 'PURCHASES', 'CASH_ADVANCE',
        'CREDIT_LIMIT', 'PAYMENTS', 'MINIMUM_PAYMENTS',
        'PURCHASES_TRX', 'CASH_ADVANCE_TRX', 'TENURE'
    ]
    for col in outliers_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        # Cap values instead of removing
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df  # ✅ outside the loop

def scale_features(df):
    scaler = StandardScaler()
    scaled_array = scaler.fit_transform(df)
    scaled_df = pd.DataFrame(scaled_array, columns=df.columns)
    return scaled_df, scaler

def preprocess_pipeline(path):
    df = load_data(path)
    df = remove_unnecessary_columns(df)   # Step 1 - drop CUST_ID
    df = handle_missing_values(df)         # Step 2 - fill nulls
    df = handle_outliers(df)               # Step 3 - cap outliers
    return df

